language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 1bcab4aa72add299d72fbea0cf28c42768527a2f
 local_dir: dist
 on:
   branch: master