language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: process.env.VUE_APP_GITHUBKEY
 local_dir: dist
 on:
   branch: master